var shaderSource = [
'Shader "VRChat/VRCOpenWatch"',
'{',
'    Properties',
'    {',
'        [Toggle] _UseLocalTime ("Use viewer local time (1) or UTC (0)", Float) = 1',
'        [Enum(HH_MM_SS_24h,0,HH_MM_24h,1,MM_SS,2,HH_MM_12h_AMPM,3)] _ClockFormat ("Clock format", Float) = 0',
'',
'        [Header(Emissive Nixie Screen)]',
'        _DigitAtlas ("Digit Atlas (0-9, :, A, P, M, blank — 15 cells in row)", 2D) = "white" {}',
'        [Toggle] _UseEmission ("Use Emission", Float) = 1',
'        _EmissionIntensity ("Emission Intensity", Range(0, 10)) = 2.0',
'        [HDR] _EmissionColorA ("Emission Color A (hot end)", Color) = (0.2, 0.83, 0.6, 1.0)',
'        [HDR] _EmissionColorB ("Emission Color B (faded end)", Color) = (0.03, 0.05, 0.08, 1.0)',
'        [Enum(Vertical,0,Horizontal,1,Radial,2)] _EmissionGradientMode ("Emission Gradient Mode", Float) = 0',
'        _EmissionGradientPow ("Emission Gradient Power", Range(0.1, 8.0)) = 1.5',
'        _DigitTint ("Digit Color Tint", Color) = (1, 1, 1, 1)',
'    }',
'    SubShader',
'    {',
'        Tags',
'        {',
'            "RenderType"="Transparent"',
'            "Queue"="Transparent"',
'        }',
'        Pass',
'        {',
'            Blend SrcAlpha OneMinusSrcAlpha',
'            ZWrite Off',
'            Cull Off',
'            CGPROGRAM',
'            #pragma vertex vert',
'            #pragma fragment frag',
'            #include "UnityCG.cginc"',
'            #include "Packages/com.vrchat.base/ShaderLibrary/VRCTime.cginc"',
'',
'            #define CHAR_COLON 10',
'            #define CHAR_A 11',
'            #define CHAR_P 12',
'            #define CHAR_M 13',
'            #define CHAR_BLANK 14',
'            #define ATLAS_CHAR_COUNT 15',
'',
'            sampler2D _DigitAtlas;',
'            float _UseLocalTime;',
'            float _ClockFormat;',
'            float _UseEmission;',
'            float _EmissionIntensity;',
'            float4 _EmissionColorA;',
'            float4 _EmissionColorB;',
'            float _EmissionGradientMode;',
'            float _EmissionGradientPow;',
'            float4 _DigitTint;',
'',
'            struct appdata',
'            {',
'                float4 vertex : POSITION;',
'                float2 uv : TEXCOORD0;',
'            };',
'',
'            struct v2f',
'            {',
'                float4 vertex : SV_POSITION;',
'                float2 uv : TEXCOORD0;',
'            };',
'',
'            v2f vert(appdata v)',
'            {',
'                v2f o;',
'                o.vertex = UnityObjectToClipPos(v.vertex);',
'                o.uv = v.uv;',
'                return o;',
'            }',
'',
'            fixed4 frag(v2f i) : SV_Target',
'            {',
'                uint hours, minutes, seconds, milliseconds;',
'',
'                if (_UseLocalTime > 0.5)',
'                {',
'                    VRC_GetLocalTime(hours, minutes, seconds, milliseconds);',
'                }',
'                else',
'                {',
'                    VRC_GetUTCTime(hours, minutes, seconds, milliseconds);',
'                }',
'',
'                uint slots[8];',
'                uint totalSlots = 8;',
'',
'                int fmt = (int)round(_ClockFormat);',
'',
'                if (fmt == 0)',
'                {',
'                    totalSlots = 8;',
'                    slots[0] = hours / 10;   slots[1] = hours % 10;   slots[2] = CHAR_COLON;',
'                    slots[3] = minutes / 10; slots[4] = minutes % 10; slots[5] = CHAR_COLON;',
'                    slots[6] = seconds / 10; slots[7] = seconds % 10;',
'                }',
'                else if (fmt == 1)',
'                {',
'                    totalSlots = 5;',
'                    slots[0] = hours / 10;   slots[1] = hours % 10;   slots[2] = CHAR_COLON;',
'                    slots[3] = minutes / 10; slots[4] = minutes % 10;',
'                }',
'                else if (fmt == 2)',
'                {',
'                    totalSlots = 5;',
'                    slots[0] = minutes / 10; slots[1] = minutes % 10; slots[2] = CHAR_COLON;',
'                    slots[3] = seconds / 10; slots[4] = seconds % 10;',
'                }',
'                else',
'                {',
'                    uint h12 = hours % 12;',
'                    if (h12 == 0) h12 = 12;',
'                    bool isPM = hours >= 12;',
'',
'                    totalSlots = 8;',
'                    slots[0] = h12 / 10;     slots[1] = h12 % 10;     slots[2] = CHAR_COLON;',
'                    slots[3] = minutes / 10; slots[4] = minutes % 10; slots[5] = CHAR_BLANK;',
'                    slots[6] = isPM ? CHAR_P : CHAR_A;',
'                    slots[7] = CHAR_M;',
'                }',
'',
'                uint slotIndex = (uint)floor(i.uv.x * totalSlots);',
'                if (slotIndex >= totalSlots) slotIndex = totalSlots - 1;',
'',
'                float localX = frac(i.uv.x * totalSlots);',
'                uint charIndex = slots[slotIndex];',
'',
'                float atlasCellWidth = 1.0 / ATLAS_CHAR_COUNT;',
'                float2 atlasUV = float2(',
'                    localX * atlasCellWidth + charIndex * atlasCellWidth,',
'                    i.uv.y',
'                );',
'',
'                fixed4 digit = tex2D(_DigitAtlas, atlasUV) * _DigitTint;',
'',
'                float lum = dot(digit.rgb, fixed3(0.299, 0.587, 0.114));',
'',
'                float2 localUV = float2(localX, i.uv.y);',
'                float gt;',
'                if (_EmissionGradientMode < 0.5)',
'                    gt = 1.0 - localUV.y;',
'                else if (_EmissionGradientMode < 1.5)',
'                    gt = localUV.x;',
'                else',
'                    gt = 1.0 - length(localUV - 0.5) * 2.0;',
'                gt = saturate(pow(saturate(gt), _EmissionGradientPow));',
'',
'                fixed3 gradCol = lerp(_EmissionColorB.rgb, _EmissionColorA.rgb, gt);',
'                if (_UseEmission > 0.5)',
'                    digit.rgb += lum * gradCol * _EmissionIntensity;',
'',
'                clip(digit.a - 0.001);',
'                return digit;',
'            }',
'            ENDCG',
'        }',
'    }',
'}'
].join('\n');

document.getElementById('shaderCode').textContent = shaderSource;
function fmtSlotVec(slot) {
  if (!slot) return '(0, 0, 0, 0)';
  return '(' + slot.uMin.toFixed(5) + ', ' + slot.vMin.toFixed(5) + ', ' + slot.uMax.toFixed(5) + ', ' + slot.vMax.toFixed(5) + ')';
}

function generateCustomUvClockShader() {
  var fmt = parseInt(clockFormatInput.value) || 0;
  var s = [0, 1, 2, 3, 4, 5, 6, 7].map(function(i) { return fmtSlotVec(uvSlots[i]); });
  return [
    'Shader "VRChat/VRCOpenWatch/CustomUV"',
    '{',
'    Properties',
'    {',
'        _DigitAtlas ("Digit Atlas (0-9, :, A, P, M, blank — 15 cells)", 2D) = "white" {}',
'        [Toggle] _UseLocalTime ("Use viewer local time (1) or UTC (0)", Float) = 1',
'        [Enum(HH_MM_SS_24h,0,HH_MM_24h,1,MM_SS,2,HH_MM_12h_AMPM,3)] _ClockFormat ("Clock format", Float) = ' + fmt,
'        _Slot0 ("Slot 0 UV minXY maxXY", Vector) = ' + s[0],
'        _Slot1 ("Slot 1 UV minXY maxXY", Vector) = ' + s[1],
'        _Slot2 ("Slot 2 UV minXY maxXY", Vector) = ' + s[2],
'        _Slot3 ("Slot 3 UV minXY maxXY", Vector) = ' + s[3],
'        _Slot4 ("Slot 4 UV minXY maxXY", Vector) = ' + s[4],
'        _Slot5 ("Slot 5 UV minXY maxXY", Vector) = ' + s[5],
'        _Slot6 ("Slot 6 UV minXY maxXY", Vector) = ' + s[6],
'        _Slot7 ("Slot 7 UV minXY maxXY", Vector) = ' + s[7],
'',
'        [Header(Emissive Nixie Screen)]',
'        [Toggle] _UseEmission ("Use Emission", Float) = 1',
'        _EmissionIntensity ("Emission Intensity", Range(0, 10)) = 2.0',
'        [HDR] _EmissionColorA ("Emission Color A (hot end)", Color) = (0.2, 0.83, 0.6, 1.0)',
'        [HDR] _EmissionColorB ("Emission Color B (faded end)", Color) = (0.03, 0.05, 0.08, 1.0)',
'        [Enum(Vertical,0,Horizontal,1,Radial,2)] _EmissionGradientMode ("Emission Gradient Mode", Float) = 0',
'        _EmissionGradientPow ("Emission Gradient Power", Range(0.1, 8.0)) = 1.5',
'        _DigitTint ("Digit Color Tint", Color) = (1, 1, 1, 1)',
'    }',
'    SubShader',
'    {',
'        Tags { "RenderType"="Transparent" "Queue"="Transparent" }',
'        Pass',
'        {',
'            Blend SrcAlpha OneMinusSrcAlpha',
'            ZWrite Off',
'            Cull Off',
'            CGPROGRAM',
    '            #pragma vertex vert',
    '            #pragma fragment frag',
    '            #include "UnityCG.cginc"',
    '            #include "Packages/com.vrchat.base/ShaderLibrary/VRCTime.cginc"',
    '',
    '            #define CHAR_COLON 10',
    '            #define CHAR_A 11',
    '            #define CHAR_P 12',
    '            #define CHAR_M 13',
    '            #define CHAR_BLANK 14',
    '            #define ATLAS_CHAR_COUNT 15',
    '',
'            sampler2D _DigitAtlas;',
'            float _UseLocalTime;',
'            float _ClockFormat;',
'            float4 _Slot0;',
'            float4 _Slot1;',
'            float4 _Slot2;',
'            float4 _Slot3;',
'            float4 _Slot4;',
'            float4 _Slot5;',
'            float4 _Slot6;',
'            float4 _Slot7;',
'            float _UseEmission;',
'            float _EmissionIntensity;',
'            float4 _EmissionColorA;',
'            float4 _EmissionColorB;',
'            float _EmissionGradientMode;',
'            float _EmissionGradientPow;',
'            float4 _DigitTint;',
    '',
    '            struct appdata { float4 vertex : POSITION; float2 uv : TEXCOORD0; };',
    '            struct v2f { float4 vertex : SV_POSITION; float2 uv : TEXCOORD0; };',
    '',
    '            v2f vert(appdata v)',
    '            {',
    '                v2f o;',
    '                o.vertex = UnityObjectToClipPos(v.vertex);',
    '                o.uv = v.uv;',
    '                return o;',
    '            }',
    '',
    '            bool SlotHit(float4 r, float2 uv, out float2 localUV)',
    '            {',
    '                localUV = float2(0, 0);',
    '                float w = r.z - r.x;',
    '                float h = r.w - r.y;',
    '                if (w < 1e-5 || h < 1e-5) return false;',
    '                if (uv.x < r.x || uv.x > r.z || uv.y < r.y || uv.y > r.w) return false;',
    '                localUV = float2((uv.x - r.x) / w, (uv.y - r.y) / h);',
    '                return true;',
    '            }',
    '',
    '            fixed4 frag(v2f i) : SV_Target',
    '            {',
    '                uint hours, minutes, seconds, milliseconds;',
    '                if (_UseLocalTime > 0.5)',
    '                    VRC_GetLocalTime(hours, minutes, seconds, milliseconds);',
    '                else',
    '                    VRC_GetUTCTime(hours, minutes, seconds, milliseconds);',
    '',
    '                uint slots[8];',
    '                uint totalSlots = 8;',
    '                int fmt = (int)round(_ClockFormat);',
    '',
    '                if (fmt == 0)',
    '                {',
    '                    totalSlots = 8;',
    '                    slots[0] = hours / 10;   slots[1] = hours % 10;   slots[2] = CHAR_COLON;',
    '                    slots[3] = minutes / 10; slots[4] = minutes % 10; slots[5] = CHAR_COLON;',
    '                    slots[6] = seconds / 10; slots[7] = seconds % 10;',
    '                }',
    '                else if (fmt == 1)',
    '                {',
    '                    totalSlots = 5;',
    '                    slots[0] = hours / 10;   slots[1] = hours % 10;   slots[2] = CHAR_COLON;',
    '                    slots[3] = minutes / 10; slots[4] = minutes % 10;',
    '                }',
    '                else if (fmt == 2)',
    '                {',
    '                    totalSlots = 5;',
    '                    slots[0] = minutes / 10; slots[1] = minutes % 10; slots[2] = CHAR_COLON;',
    '                    slots[3] = seconds / 10; slots[4] = seconds % 10;',
    '                }',
    '                else',
    '                {',
    '                    uint h12 = hours % 12;',
    '                    if (h12 == 0) h12 = 12;',
    '                    bool isPM = hours >= 12;',
    '                    totalSlots = 8;',
    '                    slots[0] = h12 / 10;     slots[1] = h12 % 10;     slots[2] = CHAR_COLON;',
    '                    slots[3] = minutes / 10; slots[4] = minutes % 10; slots[5] = CHAR_BLANK;',
    '                    slots[6] = isPM ? CHAR_P : CHAR_A;',
    '                    slots[7] = CHAR_M;',
    '                }',
    '',
    '                float2 localUV;',
    '                int found = -1;',
    '                if (totalSlots > 0 && SlotHit(_Slot0, i.uv, localUV)) found = 0;',
    '                else if (totalSlots > 1 && SlotHit(_Slot1, i.uv, localUV)) found = 1;',
    '                else if (totalSlots > 2 && SlotHit(_Slot2, i.uv, localUV)) found = 2;',
    '                else if (totalSlots > 3 && SlotHit(_Slot3, i.uv, localUV)) found = 3;',
    '                else if (totalSlots > 4 && SlotHit(_Slot4, i.uv, localUV)) found = 4;',
    '                else if (totalSlots > 5 && SlotHit(_Slot5, i.uv, localUV)) found = 5;',
    '                else if (totalSlots > 6 && SlotHit(_Slot6, i.uv, localUV)) found = 6;',
    '                else if (totalSlots > 7 && SlotHit(_Slot7, i.uv, localUV)) found = 7;',
    '',
'                if (found < 0)',
'                    return fixed4(0, 0, 0, 0);',
'',
'                uint charIndex = slots[found];',
'                float atlasCellWidth = 1.0 / ATLAS_CHAR_COUNT;',
'                float2 atlasUV = float2(localUV.x * atlasCellWidth + charIndex * atlasCellWidth, localUV.y);',
'                fixed4 digit = tex2D(_DigitAtlas, atlasUV) * _DigitTint;',
'',
'                float lum = dot(digit.rgb, fixed3(0.299, 0.587, 0.114));',
'',
'                float gt;',
'                if (_EmissionGradientMode < 0.5)',
'                    gt = 1.0 - localUV.y;',
'                else if (_EmissionGradientMode < 1.5)',
'                    gt = localUV.x;',
'                else',
'                    gt = 1.0 - length(localUV - 0.5) * 2.0;',
'                gt = saturate(pow(saturate(gt), _EmissionGradientPow));',
'',
'                fixed3 gradCol = lerp(_EmissionColorB.rgb, _EmissionColorA.rgb, gt);',
'                if (_UseEmission > 0.5)',
'                    digit.rgb += lum * gradCol * _EmissionIntensity;',
'',
'                clip(digit.a - 0.001);',
'                return digit;',
'            }',
    '            ENDCG',
    '        }',
    '    }',
    '}'
  ].join('\n');
}

function getActiveShaderSource() {
  if (currentMode === 'flipbook') return generateFlipbookShader();
  if (clockMapping === 'custom') return generateCustomUvClockShader();
  return shaderSource;
}

function refreshShaderPreview() {
  var pre = document.getElementById('shaderCode');
  if (pre) pre.textContent = getActiveShaderSource();
}
/* ===== FLIPBOOK: SHADER GENERATION ===== */
function generateFlipbookShader() {
  var total = flipbookFrames.length;
  var cols = parseInt(gridColsInput.value) || 4;
  var rows = Math.ceil(total / cols) || 1;
  var fps = parseInt(animFpsInput.value) || 12;
  var loop = animLoopInput.checked ? 1 : 0;
  var pingPong = animPingPongInput.checked ? 1 : 0;
  return [
    'Shader "VRChat/VRCOpenWatch/Flipbook"',
    '{',
    '    Properties',
    '    {',
    '        _MainTex ("Sprite Sheet (' + cols + 'x' + rows + ', ' + total + ' frames)", 2D) = "white" {}',
    '        _FrameCount ("Total Frames", Float) = ' + total,
    '        _FPS ("Frames Per Second", Float) = ' + fps,
    '        _Columns ("Grid Columns", Float) = ' + cols,
    '        _Rows ("Grid Rows", Float) = ' + rows,
    '        _Loop ("Loop (1) or Once (0)", Float) = ' + loop,
    '        _PingPong ("Ping-pong (1) or Normal (0)", Float) = ' + pingPong,
    '    }',
    '    SubShader',
    '    {',
    '        Tags { "RenderType"="Opaque" "Queue"="Geometry" }',
    '        Pass',
    '        {',
    '            CGPROGRAM',
    '            #pragma vertex vert',
    '            #pragma fragment frag',
    '            #include "UnityCG.cginc"',
    '',
    '            sampler2D _MainTex;',
    '            float _FrameCount;',
    '            float _FPS;',
    '            float _Columns;',
    '            float _Rows;',
    '            float _Loop;',
    '            float _PingPong;',
    '',
    '            struct appdata { float4 vertex : POSITION; float2 uv : TEXCOORD0; };',
    '            struct v2f { float4 vertex : SV_POSITION; float2 uv : TEXCOORD0; };',
    '',
    '            v2f vert(appdata v)',
    '            {',
    '                v2f o;',
    '                o.vertex = UnityObjectToClipPos(v.vertex);',
    '                o.uv = v.uv;',
    '                return o;',
    '            }',
    '',
    '            fixed4 frag(v2f i) : SV_Target',
    '            {',
    '                float totalFrames = _FrameCount;',
    '                if (totalFrames <= 0.5) return tex2D(_MainTex, i.uv);',
    '',
    '                float frame;',
    '                if (_PingPong > 0.5)',
    '                {',
    '                    float cycle = _Time.y * _FPS;',
    '                    float period = max(1.0, (totalFrames - 1.0) * 2.0);',
    '                    float pos = fmod(cycle, period);',
    '                    frame = pos < totalFrames ? floor(pos) : period - floor(pos);',
    '                }',
    '                else',
    '                {',
    '                    frame = floor(_Time.y * _FPS);',
    '                    if (_Loop < 0.5)',
    '                    {',
    '                        frame = min(frame, totalFrames - 1.0);',
    '                    }',
    '                    frame = fmod(frame, totalFrames);',
    '                }',
    '',
    '                float cols = max(1.0, _Columns);',
    '                float rows = max(1.0, _Rows);',
    '                float col = fmod(frame, cols);',
    '                float row = floor(frame / cols);',
    '',
    '                float u = (col + frac(i.uv.x)) / cols;',
    '                float v = (rows - 1.0 - row + frac(i.uv.y)) / rows;',
    '                float2 atlasUV = float2(u, v);',
    '',
    '                return tex2D(_MainTex, atlasUV);',
    '            }',
    '            ENDCG',
    '        }',
    '    }',
    '}'
  ].join('\n');
}

/* ===== FLIPBOOK: EXPORT ===== */
function updateFlipbookShader() {
  refreshShaderPreview();
}